apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    helm.sh/chart: demo-0.0.1
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo
    app.kubernetes.io/version: "appVersion"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
      app.kubernetes.io/instance: demo
  template:
    metadata:
      labels:
        app: demo
        app.kubernetes.io/name: demo
        app.kubernetes.io/instance: demo
    spec:
      serviceAccountName: demo-python-serviceaccount
      containers:
        - name: demo
          securityContext:
            {}
          image: "image-name"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DD_TRACE_AGENT_URL
              value: "unix:///var/run/datadog/apm.socket"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_SERVICE
              value: demo
            - name: DD_VERSION
              value: appVersion
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health
              port: http
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - demo
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath