apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
      app.kubernetes.io/instance: demo